name: ci-exercise
on:
  pull_request:
    branches:
      - develop 

jobs:
  check-application:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: 18
      - run: npm run test
      - run: npm run math.js