name: ci-exercise
on:
  pull_request:
    branches:
      - develop 

jobs:
  check-application:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
           node-version: 18
      - name: Install dependencies
        run: npm install
      - run: npm run test
      - run: npm run start
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}